### ISSUE TITLE
ORDER BY requires sorting before LIMIT is used

### ISSUE THREAD

**Issue by JervenBolleman** [pyvandenbussche/sparqles#11]
The eval code uses rdf:type. This can be a significant load in IO for an endpoint.
Some datasets might not even have have this predicate in it. Leading to incorrect conclusions about the stability of the endpoint.

Suggest that if present you use named graphs from the VOID file to select the smallest graph or submit a small list using VALUES for sorting.

**Comment by cbuil** [comment]
we removed this problematic query and we applied your suggestion to other queries.
