### ISSUE TITLE
Document the queries used

### ISSUE THREAD

**Issue by VladimirAlexiev** [pyvandenbussche/sparqles#22]
I wonder why we got so many reds in the Interoperability report for eg http://sparqles.okfn.org/endpoint/http%3A%2F%2Flinkedlifedata.com%2Fsparql. So I want to investigate the queries (like, run them).
But the query only appears in a tooltip, so I can only get it from the HTML source (yuck!)

Please document the queries somewhere we can easily get them (and link to the report page above).

This page would be perfect: https://github.com/pyvandenbussche/sparqles/wiki/Interoperability (currently lists only the query codes)

**Comment by cbuil** [comment]
they were documented some time ago.

**Comment by VladimirAlexiev** [comment]
@cbuil I still don't see a link to the queries, eg at http://sparqles.ai.wu.ac.at/endpoint?uri=http%3A%2F%2Flinkedlifedata.com%2Fsparql

**Comment by cbuil** [comment]
They are in a tooltip, when the pointer is over the name of the query it is possible to see a brief description of it. The queries are also in the repo: https://github.com/pyvandenbussche/sparqles/tree/master/src/main/resources/ftask

I will reopen the issue to add these queries to the wiki if you want.

**Comment by VladimirAlexiev** [comment]
The problem with the tooltip is that you can't copy it out to try it.
No need to duplicate in a wiki: just add a link from http://sparqles.ai.wu.ac.at/endpoint to https://github.com/pyvandenbussche/sparqles/tree/master/src/main/resources/ftask saying eg "Get the test queries here".

Cheers!
