### ISSUE TITLE
Optimize Interoperability queries

### ISSUE THREAD

**Issue by VladimirAlexiev** [pyvandenbussche/sparqles#23]
OWLIM/Forest have full SPARQL 1.1. support. 
So I wondered why we got so many reds in the Interoperability report for eg http://sparqles.okfn.org/endpoint/http%3A%2F%2Ffactforge.net%2Fsparql. 
I investigated a bit (despite #22)L I tried the first  query:
`SELECT (MAX(?o) AS ?max) WHERE {?s rdf:type ?o} LIMIT 100`
on http://www.factforge.net/sparql and it's very slow (2-3 min). No wonder you timeout and report it as "query not supported". The query is also slow on http://www.linkedlifedata.com/sparql. It's fast on http://vocab.getty.edu/sparql, but because that db is much smaller.

Aren't Interop queries supposed to be O(1)? They test support for specific SPARQL features, not performance, right? Well, the above query is quite expensive in OWLIM: it has to fetch all ?o and look for the max URI. 

Rewriting the query to this:
`select (max(?x) as ?max) {{?x a rdfs:Class} union {?x a owl:Class}}`
makes it instantaneous.

Please revise these queries (at least the ones that come up red for our endpoints :-)) or at least give a much bigger timeout

**Comment by cbuil** [comment]
We substituted all complex queries others way simpler. regarding SELECT (MAX(?x) AS ?max) WHERE { } it does not work in Dbpedia since ?x is not a variable in the WHERE.

**Comment by VladimirAlexiev** [comment]
Good, I checked SEL[SUM] and it runs instantaneously. But it still returns red: see #41
