### ISSUE TITLE
sel[avg] could be friendlier to endpoints

### ISSUE THREAD

**Issue by JervenBolleman** [pyvandenbussche/sparqles#28]
```sparql
SELECT (AVG(?o) AS ?avg)
WHERE{
 ?s rdf:type ?o}
 LIMIT 100
```

Using submitted data instead of data in the endpoint guarantees the queries are equivalent for all endpoints. e.g.

```sparql
SELECT (AVG(?no) as ?avg)
WHERE
{
		VALUES (?no) {(1) (2) (2) (4) (4) (4) (4)} 
}
```

Same for self[avg]*order by

```sparql
SELECT (AVG(?no) as ?avg)
WHERE
{
		VALUES (?no) {(1) (2) (2) (4) (4) (4) (4)} 
} GROUP BY ?no
```

**Comment by cbuil** [comment]
unfortunately the empty WHERE clause returns errors in DBpedia since Virtuoso complains of a variable in the SELECT which is not in the WHERE clause. Agree with Aidan. We create simpler queries with subjects that do not exist in the endpoints.
