### ISSUE TITLE
Availability graph isn't updating on the front page

### ISSUE THREAD

**Issue by cbuil** [pyvandenbussche/sparqles#30]
Recently, it doesn't seem to be updating anymore, the availability graph isn't updating on the front page, and my own endpoint in there
http://sparqles.okfn.org/endpoint?uri=http%3A%2F%2Fdata.lenka.no%2Fsparql
has just a single data point, back in november.

**Comment by pyvandenbussche** [comment]
Availability diagram on the frontpage is now up to date.

**Comment by VladimirAlexiev** [comment]
@pyvandenbussche Even all-green endpoints like http://sparqles.ai.wu.ac.at/endpoint?uri=http%3A%2F%2F202.45.139.84%3A10035%2Fcatalogs%2Ffao%2Frepositories%2Fagris don't show a graph but a single point for Availability.

Can you share a link of a graph that looks the way it should?
Agree with @cbuil about this one
