### ISSUE TITLE
SPARQL Interoperability results are false for linkedlifedata.com

### ISSUE THREAD

**Issue by VladimirAlexiev** [pyvandenbussche/sparqles#41]
http://sparqles.ai.wu.ac.at/endpoint?uri=http%3A%2F%2Flinkedlifedata.com%2Fsparql reports all red for Interoperability.
I tried one of the queries, (SEL[SUM]) https://github.com/pyvandenbussche/sparqles/blob/master/src/main/resources/ftask/sparql11/SEL%5BSUM%5D.rq on http://linkedlifedata.com/sparql and it ran instantaneously and returned sum=0. 
Could you please debug why the red?

**Comment by lmatteis** [comment]
Hi @VladimirAlexiev. We had some server problems and also some minor code issues. As you can see this was fixed and he logs should be producing good results. I'll close this.

**Comment by VladimirAlexiev** [comment]
Ok, how about http://sparqles.ai.wu.ac.at/endpoint?uri=http%3A%2F%2Fvocab.getty.edu%2Fsparql ?
It runs pretty more or less the same software.
Maybe related to #42
