### ISSUE TITLE
Tooltips don't escape queries properly

### ISSUE THREAD

**Issue by rvesse** [pyvandenbussche/sparqles#43]
As noted in #22 queries are now visible in tooltips however they do not escape queries so if queries contain URIs in `<uri>` form these will not display correctly per the screenshot below (the `SERVICE` URI is missing):

![screen shot 2015-07-22 at 15 41 33 png](https://cloud.githubusercontent.com/assets/2104864/8828147/869b7bb8-3088-11e5-81f7-8f24124ccf72.jpg)

The UI needs to escape queries appropriately

**Comment by lmatteis** [comment]
Sorry for the late reply. This has been fixed.
